### ISSUE TITLE
Hardware recommendations?

### ISSUE THREAD

**Issue by jenshorn** [vinnyspb/esphome-comfortzone#1]
It would be interesting to know a bit more regarding what hardware part you are using in your setup? I noticed you are using a 32 bit Lolin S2 Mini, what other parts are you using as well? Do you have any schematics available?

**Comment by vinnyspb** [comment]
I don't have schematics unfortunately, but it consists just of 2 components:

- [Wemos S2 mini](https://www.wemos.cc/en/latest/s2/s2_mini.html)
- [RS485 module](https://www.aliexpress.com/item/32846149743.html)

**Comment by jenshorn** [comment]
Thanks for the information! I've ordered the S2 mini and I think I might have one of those RS485 modules laying around. I used the Wemos D1 Mini previously and that needed some voltage converter as well, at least the module I tried. This looks simpler.
