### ISSUE TITLE
esp32 services either crash the board or has no effect on the CZ.

### ISSUE THREAD

**Issue by pinussen** [vinnyspb/esphome-comfortzone#6]
I have a problem that the esp32 seems to either not do anything or reboot when I send a command to the CZ. I.e. use a service. The only thing that works is the debug reroute. Sensor offset or override doesn't crash the board but nothing is changed in the CZ. Fireplace on/off or my own set_room_temperature causes the esp32 to reboot.

Any tips on how to trouble shoot this? Would be nice to see the output from the "cz->" commands. 

services:
    - service: set_sensor_offset
      variables:
        sensor_num: int
        offset: float
      then:
        - lambda: |-
            auto cz = esphome::comfortzone::ComfortzoneComponent::get_singleton(id(uart_bus), $de_pin);
            cz->set_sensor_offset(sensor_num, offset);
    - service: override_indoor_temperature
      variables:
        current_temperature: float
      then:
        - lambda: |-
            auto cz = esphome::comfortzone::ComfortzoneComponent::get_singleton(id(uart_bus), $de_pin);
            cz->override_indoor_temperature(current_temperature);
    - service: debug_reroute
      variables:
        ip: string
        port: int
        timeout: int
      then:
        - lambda: |-
            auto cz = esphome::comfortzone::ComfortzoneComponent::get_singleton(id(uart_bus), $de_pin);
            cz->debug_reroute(ip, port, timeout);
    - service: enable_fireplace_mode
      then:
        - lambda: |-
            auto cz = esphome::comfortzone::ComfortzoneComponent::get_singleton(id(uart_bus), $de_pin);
            cz->set_fireplace_mode(true);
    - service: disable_fireplace_mode
      then:
        - lambda: |-
            auto cz = esphome::comfortzone::ComfortzoneComponent::get_singleton(id(uart_bus), $de_pin);
            cz->set_fireplace_mode(false);
    - service: set_room_temperature
      variables:
        temperature_setting: float
      then:
        - lambda: |-
            auto cz = esphome::comfortzone::ComfortzoneComponent::get_singleton(id(uart_bus), $de_pin);
            cz->set_room_temperature(temperature_setting);

**Comment by vinnyspb** [comment]
Hi @pinussen,

It sounds to me like some wiring problem. To get some more logging you can enable `DEBUG` logs in your YAML config:

```yaml
logger:
  level: INFO
```

Would be also helpful if you have a schematic of your setup.

**Comment by pinussen** [comment]
Hadn't though about the wiring actually, could be. 

Debug does not show much, I just get the error from comfortzone_esphome.cpp. 

[22:10:12][D][climate:396]: 'ComfortZone EX50 hot water' - Sending state:
[22:10:12][D][climate:399]:   Mode: OFF
[22:10:12][D][climate:419]:   Current Temperature: 49.70°C
[22:10:12][D][climate:425]:   Target Temperature: 70.00°C
[22:10:14][E][ComfortzoneComponent:541]: Setting requested room temp to temp 23.000000
WARNING comfortzone @ 192.168.1.56: Connection error occurred: [Errno 104] Connection reset by peer
INFO Processing unexpected disconnect from ESPHome API for comfortzone @ 192.168.1.56
WARNING Disconnected from API
INFO Successfully connected to comfortzone @ 192.168.1.56 in 0.009s
INFO Successful handshake with comfortzone @ 192.168.1.56 in 0.195s

Debug is actually a little strange, the first time it always fail. Second time it works

[22:16:02][D][climate:425]:   Target Temperature: 70.00°C
[22:16:02][E][ComfortzoneComponent:469]: Debugging enabled, forwarding to 192.168.1.84:9999 for 100 seconds
[22:16:02][E][ComfortzoneComponent:367]: Error occurred during sending: errno 12
[22:16:02][E][ComfortzoneComponent:353]: Shutting down debug socket
[22:16:02][E][ComfortzoneComponent:359]: Debugging disabled
[22:16:05][D][sensor:094]: 'Outdoor temperature': Sending state -3.00000 °C with 1 decimals of accuracy

[22:16:41][D][climate:425]:   Target Temperature: 23.00°C
[22:16:41][E][ComfortzoneComponent:469]: Debugging enabled, forwarding to 192.168.1.84:9999 for 100 seconds
[22:16:41][D][sensor:094]: 'Days until filter change': Sending state 8.00000 days with 0 decimals of accuracy

Very simple wiring. I first tried to use the power from the CZ with a step down board but never got that to work. Now I feed the max485 from the esp32, vcc. 

My config:
de_pin = 21
tx 17
rx 16

esp32:
  board: wemos_d1_mini32

Not totally sure about the tx and rx in my drawing, but I can read data OK. One possible problem is that the rj12 cable seems a bit glitchy. Caused the fuse to blow once.

![PXL_20240204_181640117](https://github.com/vinnyspb/esphome-comfortzone/assets/7061224/4bdddf23-6fe0-4423-ab79-137d27d23bfe)
![PXL_20240204_181655257](https://github.com/vinnyspb/esphome-comfortzone/assets/7061224/9b815850-f182-4ad7-8cb0-5bd2c427421b)
![PXL_20240204_205634957](https://github.com/vinnyspb/esphome-comfortzone/assets/7061224/6f67c159-3739-4520-9e09-8f420759f230)
![esp32](https://github.com/vinnyspb/esphome-comfortzone/assets/7061224/bc713e4e-241b-4db6-bb29-8e1821386330)

**Comment by pinussen** [comment]
Closing this, turned out there was something strange with the cable. After redoing it, it does not crash.
